[package]
name = "atlas"
version = "0.1.0"
edition = "2024"

[dependencies]
clap.workspace = true
thiserror.workspace = true
sisyphus = { path = "../sisyphus" }
tar.workspace = true
zstd.workspace = true
ring.workspace = true
serde-saphyr.workspace = true
common.workspace = true
semver.workspace = true
walkdir.workspace = true
rustix = "1.1.5"
